// Questions
var q = [
	// Originals

	'What are you working on?', 'Why charge 2.99', 'How much money could you make per year?', 'Why isn’t someone already doing this?', 'Why will you succeed over others? What do you understand that others don’t?', 'How many users do you have?', 'Where do new users come from? How do users find out about you?', 'What is your distribution strategy? How will you grow?', 'What makes new users try you?', 'Why do the reluctant users hold back?', 'Who is going to be your first paying customer?', 'What resistance will users have to trying you and how will you overcome it?', 'What problems and hurdles are you anticipating? How will you overcome them?', 'Six months from now, what’s going to be your biggest problem?', 'Why did you choose this idea? Why did you pick this idea to work on?', 'Where is the rocket science here?', 'How does your product work in more detail?', 'What do you understand about your users? What domain expertise do you have?', 'What are the key things about your field that outsiders don’t understand?', 'What’s an impressive thing you have done?', 'How did your team meet?', 'Why did your team get together?', 'Who in your team does what?', 'Who would you hire or how would you add to your team? Who would be your next hire?', 'What part of your project are you going to build first? What are you going to do next? What is the next step with the product evolution?', 'If your startup succeeds, what additional areas might you be able to expand into?', 'Who are your competitors?', 'Who might become competitors?', 'What competition do you fear most?', 'What will you do if we don’t fund you?', 'Would you relocate to Silicon Valley during YC?', 'Who is “the boss”?', 'How do we know your team will stick together? ', 'Will your team stick at this?', 'What else have you created together?', 'Are you open to changing your idea?', 'Someone just showed us an idea like this right before you guys. I don’t like it. What else do you have?', 'What is something surprising you have done?', 'What’s the funniest thing that has happened to you?', 'What’s the worst thing that has happened? What’s the biggest mistake you have made?', 'Why haven't you quit your job?', 'What are your plans for the next year?', 'How many users in beta', 'What progress have you made since the application', 'Who is currently on your team', 'What happened to Jeff?', 'How long have you been working on this?', 'How long have you been working on this full time?', 'What have you built in the past?', 'Are people willing to pay?', 'How big an opportunity is here?', 'Who is currently on your team?', 'What other ideas are you open to?', 'What makes you different from existing options.', 'Demonstrate willingness to pay? ', 'What a good comparision product for willingness to pay?', 'How will you get your first 100 users?', 'What it the most unique aspect of your product? How is it different?', 'Why havent you quit.', 'What are you working on?', 'In what ways are you recourseful'

];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];
